<?php

declare(strict_types=1);

/**
 * Acquired.com Payments Integration for Magento2
 *
 * Copyright (c) 2024 Acquired Limited (https://acquired.com/)
 *
 * This file is open source under the MIT license.
 * Please see LICENSE file for more details.
 */
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$nonceProvider = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Csp\Helper\CspNonceProvider::class);
$nonce = $nonceProvider->generateNonce();
?>
<?php if ($block->getJsIntegrityHash()) : ?>
    <script type="text/javascript" nonce="<?= $nonce; ?>">
        window.ACQUIRED_JS_INTEGRITY_HASH = "<?= $block->escapeJs($block->getJsIntegrityHash()); ?>";
    </script>
<?php endif; ?>